<a href="https://colab.research.google.com/github/juliusmatter/PyTorch_Training/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


Creating Tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [10]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [14]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [19]:
MATRIX[1]

tensor([ 9, 10])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [25]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [26]:
TENSOR.ndim

3

In [28]:
TENSOR.shape

torch.Size([1, 3, 3])

In [29]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [35]:
TENSOR[0,2,0]

tensor(2)

In [45]:
### Why random tensors?

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9469, 0.6956, 0.5173, 0.1251],
        [0.1578, 0.9756, 0.6686, 0.0438],
        [0.5316, 0.5572, 0.8809, 0.0458]])

In [46]:
random_tensor.ndim

2

In [49]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #heigth, width, color channel
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [52]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [55]:
ones = torch.ones(size = (1,2))
ones

tensor([[1., 1.]])

In [58]:
ones.dtype

torch.float32

In [60]:
#torch.range

torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float32,
                               device = None,
                               requires_grad = False)
float_32_tensor.dtype

torch.float32

In [75]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [78]:
tensor = torch.arange(1,6)
tensor

tensor([1, 2, 3, 4, 5])

In [79]:
torch.mul(tensor, 10)

tensor([10, 20, 30, 40, 50])

In [81]:
torch.matmul(tensor, tensor)

tensor(55)

In [93]:
matrix_A = torch.rand(2,3)
matrix_A

tensor([[0.3241, 0.9102, 0.4147],
        [0.7080, 0.0854, 0.7824]])

In [94]:
matrix_B = matrix_A.T
matrix_B

tensor([[0.3241, 0.7080],
        [0.9102, 0.0854],
        [0.4147, 0.7824]])

In [95]:
torch.mm(matrix_A, matrix_B)

tensor([[1.1056, 0.6317],
        [0.6317, 1.1207]])

In [96]:
vector = torch.arange(1,10)
vector

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
vector.max()

tensor(9)

In [100]:
vector.argmin()

tensor(0)